import test from 'node:test';
import assert from 'node:assert/strict';
import {Sand} from '../src/sand.js';
import {drive,scoop,release} from '../src/simulation.js';
const toy=(kind,x=0,z=0)=>({kind,x,z,angle:0,active:false,cargo:0,arm:0});
test('scooping and releasing conserve sand',()=>{const s=new Sand(),t=toy(1);const mass=s.mass();scoop(t,s);assert.ok(t.cargo>0);assert.ok(Math.abs(s.mass()+t.cargo-mass)<.001);release(t,[t],s);assert.equal(t.cargo,0);assert.ok(Math.abs(s.mass()-mass)<.001);});
test('blade moves sand forward without creating it',()=>{const s=new Sand(),t=toy(0);t.active=true;const before=s.heights.slice(),mass=s.mass();drive(t,[t],s,new Set(['w']),.04);assert.ok(s.heights.some((v,i)=>v!==before[i]));assert.ok(Math.abs(s.mass()-mass)<.001);});
test('vehicles stay bounded and parked toys stay still',()=>{const s=new Sand(),t=toy(0),parked=toy(1,4,4);for(let i=0;i<500;i++)drive(t,[t,parked],s,new Set(['w']),.04);assert.equal(t.z,-5.25);assert.equal(parked.x,4);assert.equal(parked.z,4);});
test('truck collects and unloads with conservation',()=>{const s=new Sand(),t=toy(2);const mass=s.mass();for(let i=0;i<60;i++)drive(t,[t],s,new Set(['w']),.04);assert.ok(t.cargo>0);t.active=true;for(let i=0;i<100;i++)drive(t,[t],s,new Set(),.04);assert.equal(t.cargo,0);assert.ok(Math.abs(s.mass()-mass)<.002);});
test('digger can transfer a scoop into a parked truck',()=>{const s=new Sand(),d=toy(1),truck=toy(2,0,-1.62);scoop(d,s);const load=d.cargo;release(d,[d,truck],s);assert.equal(truck.cargo,load);assert.equal(d.cargo,0);});
test('vehicles cannot drive through another toy',()=>{const s=new Sand(),d=toy(0),other=toy(1,0,-2);for(let i=0;i<100;i++)drive(d,[d,other],s,new Set(['w']),.04);assert.ok(Math.hypot(d.x-other.x,d.z-other.z)>=1.5);});
